PR With benchmark.
Marshall483/HomeworkCalculator pull request #12
Opened 2020-12-14 15:46 UTC by Marshall483

For better understand speed working methods with different modifier.

2020-12-18 14:06 UTC, VayFull requested changes

2020-12-18 14:06 UTC, VayFull commented on MyClass.cs
> +                a += i.ToString();
т.к строка - иммутабельный тип, в подобных местах лучше пользоваться StringBuilder'ом https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=net-5.0 (и ниже тоже)

2020-12-18 14:06 UTC, VayFull commented on MyClass.cs
> +        //[Benchmark(Description = "PbGenericStaticVoid")]
комментарий

2020-12-18 14:06 UTC, VayFull commented on UnitTest1.cs
> +        public void Setup()
Зачем нужен пустой метод?

2020-12-18 14:06 UTC, VayFull commented on UnitTest1.cs
> +        public void Test1()
Зачем нужен такой тест?

2020-12-18 14:06 UTC, VayFull commented on EasiestTestClass.cs
> +        {
можно воспользоваться стрелочной функцией

2020-12-26 17:30 UTC, Marshall483 commented on UnitTest1.cs
> +        public void Setup()
Класс использовал для проверки работоспособности библиотеки. (Что должно быть выведено в качестве результата, как запустить сами тесты и тд)

2020-12-27 19:49 UTC, merged